// A file to store Warframe weapon riven dispositions

const options = [
	// Rifle Primaries
	{
		label: "Rifles",
		options: [
			{label: "Baza", value: "BAZA"},
			{label: "Boltor", value: "BOLTOR"},
			{label: "Braton", value: "BRATON"},
			{label: "Buzlok", value: "BUZLOK"},
			{label: "Dera", value: "DERA"},
			{label: "Gorgon", value: "GORGON"},
			{label: "Grakata", value: "GRAKATA"},
			{label: "Karak", value: "KARAK"},
			{label: "Mutalist Quanta", value: "MUTALIST QUANTA"},
			{label: "Soma", value: "SOMA"},
			{label: "Supra", value: "SUPRA"},
			{label: "Tetra", value: "TETRA"},
			{label: "Grinlok", value: "GRINLOK"},
			{label: "Latron", value: "LATRON"},
			{label: "Veldt", value: "VELDT"},
			{label: "Burston", value: "BURSTON"},
			{label: "Hema", value: "HEMA"},
			{label: "Paracyst", value: "PARACYST"},
			{label: "Quartakk", value: "QUARTAKK"},
			{label: "Sybaris", value: "SYBARIS"},
			{label: "Tiberon", value: "TIBERON"},
			{label: "Argonak", value: "ARGONAK"},
			{label: "Battacor", value: "BATTACOR"},
			{label: "Harpak", value: "HARPAK"},
			{label: "Hind", value: "HIND"},
			{label: "Stradavar", value: "STRADAVAR"},
			{label: "Tenora", value: "TENORA"},
			{label: "Zenith", value: "ZENITH"},
			{label: "Amprex", value: "AMPREX"},
			{label: "Flux Rifle", value: "FLUX RIFLE"},
			{label: "Glaxion", value: "GLAXION"},
			{label: "Ignis", value: "IGNIS"},
			{label: "Quanta", value: "QUANTA"},
			{label: "Synapse", value: "SYNAPSE"},
			{label: "Opticor", value: "OPTICOR"},
			{label: "Miter", value: "MITER"},
			{label: "Ogris", value: "OGRIS"},
			{label: "Panthera", value: "PANTHERA"},
			{label: "Penta", value: "PENTA"},
			{label: "Simulor", value: "SIMULOR"},
			{label: "Tonkor", value: "TONKOR"},
			{label: "Torid", value: "TORID"},
			{label: "Zarr", value: "ZARR"},
			{label: "Ferrox", value: "FERROX"},
			{label: "Javlok", value: "JAVLOK"},
			{label: "Scourge", value: "SCOURGE"},

			{label: "Rubico", value: "RUBICO"},
			{label: "Snipetron", value: "SNIPETRON"},
			{label: "Vectis", value: "VECTIS"},
			{label: "Vulkar", value: "VULKAR"},
			{label: "Lanka", value: "LANKA"},

			{label: "Attica", value: "ATTICA"},
			{label: "Zhuge", value: "ZHUGE"},
			{label: "Nagantaka", value: "NAGANTAKA"},
			{label: "Cernos", value: "CERNOS"},
			{label: "Daikyu", value: "DAIKYU"},
			{label: "Dread", value: "DREAD"},
			{label: "Lenz", value: "LENZ"},
			{label: "Paris", value: "PARIS"}
		]
	},
	{
		label: "Shotguns",
		options: [
			{label: "Astillla", value: "ASTILLA"},
			{label: "Boar", value: "BOAR"},
			{label: "Kohm", value: "KOHM"},
			{label: "Sobek", value: "SOBEK"},
			{label: "Arca Plasmor", value: "ARCA PLASMOR" },
			{label: "Corinth", value: "CORINTH"},
			{label: "Exergis", value: "EXERGIS"},
			{label: "Hek", value: "HEK"},
			{label: "Strun", value: "STRUN"},
			{label: "Tigris", value: "TIGRIS"},
			{label: "Drakgoon", value: "DRAKGOON"},
			{label: "Convectrix", value: "CONVECTRIX"},
			{label: "Phage", value: "PHAGE"},
			{label: "Phantasma", value: "PHANTASMA"},
		]
	},
	{
		label: "Pistols",
		options: [
			{label: "Azima", value: "AZIMA"},
			{label: "Cestra", value: "CESTRA"},
			{label: "Furis", value: "FURIS"},
			{label: "Hystrix", value: "HYSTRIX"},
			{label: "Stubba", value: "STUBBA"},
			{label: "Viper", value: "VIPER"},
			{label: "Acrid", value: "ACRID"},
			{label: "Arca Scisco", value: "ARCA SCISCO"},
			{label: "Bolto", value: "BOLTO"},
			{label: "Knell", value: "KNELL"},
			{label: "Lato", value: "LATO"},
			{label: "Lex", value: "LEX"},
			{label: "Magnus", value: "MAGNUS"},
			{label: "Marelok", value: "MARELOK"},
			{label: "Plinx", value: "PLINX"},
			{label: "Seer", value: "SEER"},
			{label: "Sonicor", value: "SONICOR"},
			{label: "Tysis", value: "TYSIS"},
			{label: "Vasto", value: "VASTO"},
			{label: "Zakti", value: "ZAKTI"},
			{label: "Kraken", value: "KRAKEN"},
			{label: "Sicarus", value: "SICARUS"},
			{label: "Ballistica", value: "BALLISTICA"},
			{label: "Pandero", value: "PANDERO"},
			{label: "Zylok", value: "ZYLOK"},
			{label: "Atomos", value: "ATOMOS"},
			{label: "Cycron", value: "CYCRON"},
			{label: "EMBOLIST", value: "EMBOLIST"},
			{label: "Gammacor", value: "GAMMACOR"},
			{label: "Nukor", value: "NUKOR"},
			{label: "Ocucor", value: "OCUCOR"},
			{label: "Spectra", value: "SPECTRA"},
			{label: "Brakk", value: "BRAKK"},
			{label: "Bronco", value: "BRONCO"},
			{label: "Detron", value: "DETRON"},
			{label: "Euphona Prime", value: "EUPHONA PRIME"},
			{label: "Kohmak", value: "KOHMAK"},
			{label: "Pyrana", value: "PYRANA"},
			{label: "Angstrum", value: "ANGSTRUM"},
			{label: "Kulstar", value: "KULSTAR"},
			{label: "Stug", value: "STUG"},

			{label: "Afuris", value: "AFURIS"},
			{label: "Aksomati", value: "AKSOMATI"},
			{label: "Akstiletto", value: "AKSTILETTO"},
			{label: "Akzani", value: "AKZANI"},
			{label: "Dual Cestra", value: "DUAL CESTRA"},
			{label: "Twin Grakatas", value: "TWIN GRAKATAS"},
			{label: "Twin Gremlins", value: "TWIN GREMLINS"},
			{label: "Twin Vipers", value: "TWIN VIPERS"},
			{label: "Akbolto", value: "AKBOLTO"},
			{label: "Aklato", value: "AKLATO"},
			{label: "Aklex", value: "AKLEX"},
			{label: "Akmagnus", value: "AKMAGNUS"},
			{label: "Akvasto", value: "AKVASTO"},
			{label: "Dual Toxocyst", value: "DUAL TOXOCYST"},
			{label: "Akjagara", value: "AKJAGARA"},
			{label: "Akbronco", value: "AKBRONCO"},
			{label: "Twin Kohmak", value: "TWIN KOHMAK"},
			{label: "Twin Rogga", value: "TWIN ROGGA"},
			{label: "Staticor", value: "STATICOR"},

			{label: "Castanas", value: "CASTANAS"},
			{label: "Despair", value: "DESPAIR"},
			{label: "Fusilai", value: "FUSILAI"},
			{label: "Hikou", value: "HIKOU"},
			{label: "Kunai", value: "KUNAI"},
			{label: "Pox", value: "POX"},
			{label: "Spira", value: "SPIRA"},
			{label: "Talons", value: "TALONS"}
		]
	},
	{
		label: "Kitguns",
		options: [
			{label: "Catchmoon", value: "CATCHMOON"},
			{label: "Rattleguts", value: "RATTLEGUTS"},
			{label: "Tombfinger", value: "TOMBFINGER"},
			{label: "Gaze", value: "GAZE"},
		]
	},
	{
		label: "Melee",
		options: [
			{label: "Broken War", value: "BROKEN WAR"},
			{label: "Cronus", value: "CRONUS"},
			{label: "Dakra Prime", value: "DAKRA PRIME"},
			{label: "Dark Sword", value: "DARK SWORD"},
			{label: "Ether Sword", value: "ETHER SWORD"},
			{label: "Heat Sword", value: "HEAT SWORD"},
			{label: "Jaw Sword", value: "JAW SWORD"},
			{label: "Krohkur", value: "KROHKUR"},
			{label: "Mire", value: "MIRE"},
			{label: "Pangolin Sword", value: "PANGOLIN SWORD"},
			{label: "Plasma Sword", value: "PLASMA SWORD"},
			{label: "Skana", value: "SKANA"},
			{label: "Dark Split-Sword", value: "DARK SPLIT-SWORD"},
			{label: "Dex Dakra", value: "DEX DAKRA"},
			{label: "Dual Cleavers", value: "DUAL CLEAVERS"},
			{label: "Dual Ether", value: "DUAL ETHER"},
			{label: "Dual Heat Swords", value: "DUAL HEAT SWORDS"},
			{label: "Dual Ichor", value: "DUAL ICHOR"},
			{label: "Dual Kamas", value: "DUAL KAMAS"},
			{label: "Dual Keres", value: "DUAL KERES"},
			{label: "Dual Raza", value: "DUAL RAZA"},
			{label: "Dual Skana", value: "DUAL SKANA"},
			{label: "Dual Zoren", value: "DUAL ZOREN"},
			{label: "Nami Skyla", value: "NAMI SKYLA"},
			{label: "Twin Basolk", value: "TWIN BASOLK"},
			{label: "Twin Krohkur", value: "TWIN KROHKUR"},
			{label: "Ack & Brunt", value: "ACK & BRUNT"},
			{label: "Cobra & Crane", value: "COBRA & CRANE"},
			{label: "Sigma & Octantis", value: "SIGMA & OCTANTIS"},
			{label: "Silva & Aegis", value: "SILVA & AEGIS"},
			{label: "Gazal Machete", value: "GAZAL MACHETE"},
			{label: "Kama", value: "KAMA"},
			{label: "Kreska", value: "KRESKA"},
			{label: "Machete", value: "MACHETE"},
			{label: "Nami Solo", value: "NAMI SOLO"},
			{label: "Prova", value: "PROVA"},
			{label: "Nikana", value: "NIKANA"},
			{label: "Dragon Nikana", value: "DRAGON NIKANA"},
			{label: "Skiajati", value: "SKIAJATI"},
			{label: "Destreza", value: "DESTREZA"},
			{label: "Endura", value: "ENDURA"},
			{label: "Jat Kusar", value: "JAT KUSAR"},
			{label: "Lacera", value: "LACERA"},
			{label: "Mios", value: "MIOS"},
			{label: "Tatsu", value: "TATSU"},
			{label: "Redeemer", value: "REDEEMER"},
			{label: "Sarpa", value: "SARPA"},
			{label: "Gunsen", value: "GUNSEN"},

			{label: "Ceramic Dagger", value: "CERAMIC DAGGER"},
			{label: "Dark Dagger", value: "DARK DAGGER"},
			{label: "Heat Dagger", value: "HEAT DAGGER"},
			{label: "Karyst", value: "KARYST"},
			{label: "Sheev", value: "SHEEV"},
			{label: "Ether Daggers", value: "ETHER DAGGERS"},
			{label: "Fang", value: "FANG"},
			{label: "Okina", value: "OKINA"},

			{label: "Ankyros", value: "ANKYROS"},
			{label: "Furax", value: "FURAX"},
			{label: "Tekko", value: "TEKKO"},
			{label: "Hirudo", value: "HIRUDO"},
			{label: "Kogake", value: "KOGAKE"},
			{label: "Obex", value: "OBEX"},
			{label: "Ripkas", value: "RIPKAS"},
			{label: "Venka", value: "VENKA"},

			{label: "Cassowar", value: "CASSOWAR"},
			{label: "Guandao", value: "GUANDAO"},
			{label: "Kesheg", value: "KESHEG"},
			{label: "Lesion", value: "LESION"},
			{label: "Orthos", value: "ORTHOS"},
			{label: "Pupacyst", value: "PUPACYST"},
			{label: "Serro", value: "SERRO"},
			{label: "Sydon", value: "SYDON"},
			{label: "Tonbo", value: "TONBO"},
			{label: "Amphis", value: "AMPHIS"},
			{label: "Bo", value: "BO"},
			{label: "Broken Scepter", value: "BROKEN SCEPTER"},
			{label: "Cadus", value: "CADUS"},
			{label: "Tipedo", value: "TIPEDO"},
			{label: "Anku", value: "ANKU"},
			{label: "Caustacyst", value: "CAUSTACYST"},
			{label: "Ether Reaper", value: "ETHER REAPER"},
			{label: "Hate", value: "HATE"},
			{label: "Reaper Prime", value: "REAPER PRIME"},
			{label: "Dark Split-Sword", value: "DARK SPLIT-SWORD"},
			{label: "Galatine", value: "GALATINE"},
			{label: "Gram", value: "GRAM"},
			{label: "Paracesis", value: "PARACESIS"},
			{label: "Scindo", value: "SCINDO"},
			{label: "War", value: "WAR"},
			{label: "Zenistar", value: "ZENISTAR"},
			{label: "Arca Titron", value: "ARCA TITRON"},
			{label: "Fragor", value: "FRAGOR"},
			{label: "Heliocor", value: "HELIOCOR"},
			{label: "Jat Kittag", value: "JAT KITTAG"},
			{label: "Magistar", value: "MAGISTAR"},
			{label: "Sibear", value: "SIBEAR"},
			{label: "Volnus", value: "VOLNUS"},
			{label: "Wolf Sledge", value: "WOLF SLEDGE"},

			{label: "Cerata", value: "CERATA"},
			{label: "Falcor", value: "FALCOR"},
			{label: "Glaive", value: "GLAIVE"},
			{label: "Halikar", value: "HALIKAR"},
			{label: "Kestrel", value: "KESTREL"},
			{label: "Orvius", value: "ORVIUS"},
			{label: "Boltace", value: "BOLTACE"},
			{label: "Kronen", value: "KRONEN"},
			{label: "Ohma", value: "OHMA"},
			{label: "Atterax", value: "ATTERAX"},
			{label: "Galvacord", value: "GALVACORD"},
			{label: "Lecta", value: "LECTA"},
			{label: "Scoliac", value: "SCOLIAC"},
			{label: "Ninkondi", value: "NINKONDI"},
			{label: "Shaku", value: "SHAKU"},			
		]
	},
	{
		label: "Zaw",
		options: [
			{label: "Balla", value: "BALLA"},
			{label: "Cyath", value: "CYATH"},
			{label: "Dehtat", value: "DEHTAT"},
			{label: "Dokrahm", value: "DOKRAHM"},
			{label: "Kronsh", value: "KRONSH"},
			{label: "Mewan", value: "MEWAN"},
			{label: "Ooltha", value: "OOLTHA"},
			{label: "Rabvee", value: "RABVEE"},
			{label: "Sepfahn", value: "SEPFAHN"},
			{label: "Plague Keewar", value: "PLAGUE KEEWAR"},
			{label: "Plague Kripath", value: "PLAGUE KRIPATH"},
		]
	},
	{
		label: "Robotic",
		options: [
			{label: "Deth Machine Rifle", value: "DETH MACHINE RIFLE"},
			{label: "Burst Laser", value: "BURST LASER"},
			{label: "Stinger", value: "STINGER"},
			{label: "Deconstructor", value: "DECONSTRUCTOR"},
			{label: "Vulklok", value: "VULKLOK"},
			{label: "Laser Rifle", value: "LASER RIFLE"},
			{label: "Artax", value: "ARTAX"},
			{label: "Multron", value: "MULTRON"},
			{label: "Sweeper", value: "SWEEPER"},
			{label: "Tazicor", value: "TAZICOR"},
			{label: "Vulcax", value: "VULCAX"},
		]
	}
]

export default options;